### ISSUE TITLE
Hledání podle titulku v "subjects" je pomalé

### ISSUE THREAD

**Issue by Semtexcz** [Narodni-repozitar/nr-oai-pmh-harvester#2]
# Popis problému
Karlova univerzita má v dc/subjects předmětová hesla, které se hledají v taxonomii subjects podle titulku. Hledání v databázi o cca 40 tis. heslech je pomalé a zpomaluje celý proces těžení z OAI-PMH Karlovy univerzity. 

# Příčina problému
Na extradatech existuje GIN (jsonb) index, ale z nějakého důvodu se nepoužije.

# Analýza problému
Úzké hrdlo je ve funkci find_in_json(https://github.com/Narodni-repozitar/nr-oai-pmh-harvester/blob/main/nr_oai_pmh_harvester/query.py#L14). Tato funkce produkuje query v tomto tvaru:

```SQL
SELECT *
FROM taxonomy_term
         JOIN taxonomy_taxonomy ON taxonomy_taxonomy.id = taxonomy_term.taxonomy_id
WHERE taxonomy_taxonomy.code = 'subjects'
  AND taxonomy_term.status = 'alive'
  AND (lower(CAST(taxonomy_term.extra_data AS VARCHAR)) LIKE '%%' || 'title.cs:epilepsie' || '%%')
ORDER BY taxonomy_term.slug;
```

Po zavolání EXPLAIN na tuto funkci dostaneme tento report:

```YAML
- Plan: 
    Node Type: "Sort"
    Parallel Aware: false
    Startup Cost: 4140.93
    Total Cost: 4140.93
    Plan Rows: 1
    Plan Width: 1500
    Sort Key: 
      - "taxonomy_term.slug"
    Plans: 
      - Node Type: "Nested Loop"
        Parent Relationship: "Outer"
        Parallel Aware: false
        Join Type: "Inner"
        Startup Cost: 654.36
        Total Cost: 4140.92
        Plan Rows: 1
        Plan Width: 1500
        Inner Unique: false
        Plans: 
          - Node Type: "Index Scan"
            Parent Relationship: "Outer"
            Parallel Aware: false
            Scan Direction: "Forward"
            Index Name: "ix_taxonomy_taxonomy_code"
            Relation Name: "taxonomy_taxonomy"
            Alias: "taxonomy_taxonomy"
            Startup Cost: 0.14
            Total Cost: 8.16
            Plan Rows: 1
            Plan Width: 1100
            Index Cond: "((code)::text = 'subjects'::text)"
          - Node Type: "Bitmap Heap Scan"
            Parent Relationship: "Inner"
            Parallel Aware: false
            Relation Name: "taxonomy_term"
            Alias: "taxonomy_term"
            Startup Cost: 654.22
            Total Cost: 4132.75
            Plan Rows: 1
            Plan Width: 353
            Recheck Cond: "(taxonomy_id = taxonomy_taxonomy.id)"
            Filter: "((status = 'alive'::termstatusenum) AND (lower(((extra_data)::character varying)::text) ~~ '%%title.cs:epilepsie%%'::text))"
            Plans: 
              - Node Type: "Bitmap Index Scan"
                Parent Relationship: "Outer"
                Parallel Aware: false
                Index Name: "unique_taxonomy_slug"
                Startup Cost: 0.00
                Total Cost: 654.22
                Plan Rows: 4507
                Plan Width: 0
                Index Cond: "(taxonomy_id = taxonomy_taxonomy.id)"
```

Z reportu vyplývá, že se nikdy nezavolá index na extra_data. Nezavolá se pravděpodobně z důvodu, že se nepoužije ten správný operátor, který GIN index podporuje (https://www.postgresql.org/docs/9.4/functions-json.html#FUNCTIONS-JSONB-OP-TABLE).

# Návrh řešení
Pomoct by mohlo přepsat funkci find_in_json tak, aby využívala podporované operátory, které by měly zajistit využití indexu na extra_data.

**Comment by Semtexcz** [comment]
Vyzkoušel jsem podporovanou JSONB query:
```SQL
EXPLAIN (FORMAT YAML) SELECT *
FROM taxonomy_term
         JOIN taxonomy_taxonomy ON taxonomy_taxonomy.id = taxonomy_term.taxonomy_id
WHERE taxonomy_taxonomy.code = 'subjects'
  AND taxonomy_term.status = 'alive'
  AND taxonomy_term.extra_data @> '{"title": {"cs": "epilepsie"}}'
ORDER BY taxonomy_term.slug;
```
S tímto výsledkem
```YAML
- Plan: 
    Node Type: "Sort"
    Parallel Aware: false
    Startup Cost: 245.03
    Total Cost: 245.03
    Plan Rows: 1
    Plan Width: 1500
    Sort Key: 
      - "taxonomy_term.slug"
    Plans: 
      - Node Type: "Nested Loop"
        Parent Relationship: "Outer"
        Parallel Aware: false
        Join Type: "Inner"
        Startup Cost: 40.56
        Total Cost: 245.02
        Plan Rows: 1
        Plan Width: 1500
        Inner Unique: false
        Join Filter: "(taxonomy_term.taxonomy_id = taxonomy_taxonomy.id)"
        Plans: 
          - Node Type: "Index Scan"
            Parent Relationship: "Outer"
            Parallel Aware: false
            Scan Direction: "Forward"
            Index Name: "ix_taxonomy_taxonomy_code"
            Relation Name: "taxonomy_taxonomy"
            Alias: "taxonomy_taxonomy"
            Startup Cost: 0.14
            Total Cost: 8.16
            Plan Rows: 1
            Plan Width: 1100
            Index Cond: "((code)::text = 'subjects'::text)"
          - Node Type: "Bitmap Heap Scan"
            Parent Relationship: "Inner"
            Parallel Aware: false
            Relation Name: "taxonomy_term"
            Alias: "taxonomy_term"
            Startup Cost: 40.42
            Total Cost: 236.18
            Plan Rows: 54
            Plan Width: 353
            Recheck Cond: "(extra_data @> '{\"title\": {\"cs\": \"epilepsie\"}}'::jsonb)"
            Filter: "(status = 'alive'::termstatusenum)"
            Plans: 
              - Node Type: "Bitmap Index Scan"
                Parent Relationship: "Outer"
                Parallel Aware: false
                Index Name: "json_index"
                Startup Cost: 0.00
                Total Cost: 40.41
                Plan Rows: 54
                Plan Width: 0
                Index Cond: "(extra_data @> '{\"title\": {\"cs\": \"epilepsie\"}}'::jsonb)"
```

Zdá se, že v tomto případě se použije index na extra_data.
